#!/bin/bash

#Set job requirements
#SBATCH --job-name=Clumping
#SBATCH -N 1
#SBATCH --tasks-per-node 1

#############
#module load#
#############
module load 2020
module load R/4.0.2-intel-2020a

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Cortex_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Cortex_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cortex_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Cortex_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Cortex_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Cortex_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cortex_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping"  --output="PrimeraLlengua_Brain_Cortex_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Cortex_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Cortex_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cortex_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping"  --output="Matematiques_Brain_Cortex_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Cerebellum_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellum_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellum_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Cerebellum_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Cerebellum_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellum_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellum_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Cerebellum_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Cerebellum_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellum_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellum_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Cerebellum_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Cerebellar_Hemisphere_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellar_Hemisphere_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellar_Hemisphere_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Cerebellar_Hemisphere_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Cerebellar_Hemisphere_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellar_Hemisphere_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellar_Hemisphere_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Cerebellar_Hemisphere_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Cerebellar_Hemisphere_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellar_HemisphereFE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellar_Hemisphere_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Cerebellar_Hemisphere_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Caudate_basal_ganglia_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_ Caudate_basal_ganglia_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Caudate_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Caudate_basal_ganglia_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Caudate_basal_ganglia_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_ Caudate_basal_ganglia_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Caudate_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Caudate_basal_ganglia_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Caudate_basal_ganglia_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_ Caudate_basal_ganglia_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Caudate_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Caudate_basal_ganglia_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Frontal_Cortex_BA9_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Frontal_Cortex_BA9_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Frontal_Cortex_BA9_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Frontal_Cortex_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Frontal_Cortex_BA9_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Frontal_Cortex_BA9_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Frontal_Cortex_BA9_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Frontal_Cortex_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Frontal_Cortex_BA9_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Frontal_Cortex_BA9_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Frontal_Cortex_BA9_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Frontal_Cortex_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Putamen_basal_ganglia_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Putamen_basal_ganglia_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Putamen_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Putamen_basal_ganglia_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Putamen_basal_ganglia_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Putamen_basal_ganglia_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Putamen_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Putamen_basal_ganglia_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Putamen_basal_ganglia_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Putamen_basal_ganglia_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Putamen_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Putamen_basal_ganglia_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Anterior_cingulate_cortex_BA24_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Anterior_cingulate_cortex_BA24_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Anterior_cingulate_cortex_BA24_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Anterior_cingulate_cortex_BA24_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Anterior_cingulate_cortex_BA24_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Anterior_cingulate_cortex_BA24_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Anterior_cingulate_cortex_BA24_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Anterior_cingulate_cortex_BA24_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Anterior_cingulate_cortex_BA24_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Anterior_cingulate_cortex_BA24_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Anterior_cingulate_cortex_BA24_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Anterior_cingulate_cortex_BA24_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Hypothalamus_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Hypothalamus_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hypothalamus_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Hypothalamus_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Hypothalamus_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Hypothalamus_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hypothalamus_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Hypothalamus_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Hypothalamus_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Hypothalamus_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hypothalamus_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Hypothalamus_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Hippocampus_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Hippocampus_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hippocampus_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Hippocampus_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Hippocampus_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Hippocampus_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hippocampus_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Hippocampus_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Hippocampus_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Hippocampus_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hippocampus_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Hippocampus_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Spinal_cord_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Spinal_cord_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Spinal_cord_cervical_c-1_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Spinal_cord_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Spinal_cord_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Spinal_cord_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Spinal_cord_cervical_c-1_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Spinal_cord_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Spinal_cord_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Spinal_cord_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Spinal_cord_cervical_c-1_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Spinal_cord_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Amygdala_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Amygdala_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Amygdala_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Amygdala_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Amygdala_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Amygdala_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Amygdala_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping"--output="Angles_Brain_Amygdala_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Amygdala_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Amygdala_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Amygdala_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Amygdala_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Substantia_nigra_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Substantia_nigra_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/JTI_Results_TWAS/Brain_Substantia_nigra_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Substantia_nigra_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Substantia_nigra_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Substantia_nigra_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Substantia_nigra_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Substantia_nigra_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Substantia_nigra_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Substantia_nigra_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Substantia_nigra_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Substantia_nigra_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Brain_Nucleus_accumbens_basal_ganglia_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Nucleus_accumbens_basal_ganglia_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Nucleus_accumbens_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Brain_Nucleus_accumbens_basal_ganglia_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Brain_Nucleus_accumbens_basal_ganglia_FE_predict_JTI_association_filtered.txt"  --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Nucleus_accumbens_basal_ganglia_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Nucleus_accumbens_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Brain_Nucleus_accumbens_basal_ganglia_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Brain_Nucleus_accumbens_basal_ganglia_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Brain_Nucleus_accumbens_basal_ganglia_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Nucleus_accumbens_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Brain_Nucleus_accumbens_basal_ganglia_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Matematiques_Whole_Blood_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Whole_Blood_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Whole_Blood_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Matematiques_Whole_Blood_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/PrimeraLlengua_Whole_Blood_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Whole_Blood_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Whole_Blood_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="PrimeraLlengua_Whole_Blood_Clumping"

Rscript clump_genes.r --cov_association_JTI="/home/juditc/ADHD/FE/TWAS/Angles_Whole_Blood_FE_predict_JTI_association_filtered.txt" --predict_JTI="/home/juditc/ADHD/FE/TWAS/Whole_Blood_FE_predict_JTI_filtered.txt" --pvals="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Whole_Blood_ADHD_ditte22_JTI_OR.csv" --gtf="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/Analisi_vell_Demontis_GWAS1_6/TRS/TWAS_ditte/gencode.v32lift37.annotation.gtf" --cor_threshold=0.9 --kb=500 --workingdir="/home/juditc/ADHD/FE/TWAS/Clumping" --output="Angles_Whole_Blood_Clumping"

