#!/bin/bash

#Set job requirements
#SBATCH --job-name=TRS
#SBATCH -N 1
#SBATCH --tasks-per-node 1

#############
#module load#
#############
module load 2021
module load R/4.1.0-foss-2021a

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cortex_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Cortex_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Cortex_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Cortex_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cortex_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Cortex_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Cortex_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Cortex_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cortex_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Cortex_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Cortex_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Cortex_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellum_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellum_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Cerebellum_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Cerebellum_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellum_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellum_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Cerebellum_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Cerebellum_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellum_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellum_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Cerebellum_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Cerebellum_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellar_Hemisphere_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellar_Hemisphere_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Cerebellar_Hemisphere_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Cerebellar_Hemisphere_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellar_Hemisphere_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellar_Hemisphere_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Cerebellar_Hemisphere_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Cerebellar_Hemisphere_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Cerebellar_Hemisphere_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Cerebellar_Hemisphere_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Cerebellar_Hemisphere_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Cerebellar_Hemisphere_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Caudate_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Caudate_basal_ganglia_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Caudate_basal_ganglia_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Caudate_basal_ganglia_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Caudate_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Caudate_basal_ganglia_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Caudate_basal_ganglia_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Caudate_basal_ganglia_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Caudate_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Caudate_basal_ganglia_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Caudate_basal_ganglia_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Caudate_basal_ganglia_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Frontal_Cortex_BA9_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Frontal_Cortex_BA9_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Frontal_Cortex_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Frontal_Cortex_BA9_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Frontal_Cortex_BA9_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Frontal_Cortex_BA9_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Frontal_Cortex_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Frontal_Cortex_BA9_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Frontal_Cortex_BA9_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Frontal_Cortex_BA9_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Frontal_Cortex_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Frontal_Cortex_BA9_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Putamen_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Putamen_basal_ganglia_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Putamen_basal_ganglia_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Putamen_basal_ganglia_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Putamen_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Putamen_basal_ganglia_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Putamen_basal_ganglia_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Putamen_basal_ganglia_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Putamen_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Putamen_basal_ganglia_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Putamen_basal_ganglia_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Putamen_basal_ganglia_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Anterior_cingulate_cortex_BA24_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Anterior_cingulate_cortex_BA24_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Anterior_cingulate_cortex_BA24_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Anterior_cingulate_cortex_BA24_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Anterior_cingulate_cortex_BA24_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Anterior_cingulate_cortex_BA24_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Anterior_cingulate_cortex_BA24_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Anterior_cingulate_cortex_BA24_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Anterior_cingulate_cortex_BA24_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Anterior_cingulate_cortex_BA24_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Anterior_cingulate_cortex_BA24_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Anterior_cingulate_cortex_BA24_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hypothalamus_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Hypothalamus_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Hypothalamus_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Hypothalamus_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hypothalamus_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Hypothalamus_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Hypothalamus_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Hypothalamus_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hypothalamus_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Hypothalamus_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Hypothalamus_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Hypothalamus_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hippocampus_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Hippocampus_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Hippocampus_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Hippocampus_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hippocampus_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Hippocampus_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Hippocampus_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Hippocampus_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Hippocampus_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Hippocampus_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Hippocampus_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Hippocampus_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Spinal_cord_cervical_c-1_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Spinal_cord_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Spinal_cord_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Spinal_cord_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Spinal_cord_cervical_c-1_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Spinal_cord_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Spinal_cord_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Spinal_cord_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Spinal_cord_cervical_c-1_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Spinal_cord_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Spinal_cord_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Spinal_cord_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Amygdala_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Amygdala_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Amygdala_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Amygdala_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Amygdala_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Amygdala_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Amygdala_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Amygdala_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Amygdala_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Amygdala_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Amygdala_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Amygdala_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Substantia_nigra_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Substantia_nigra_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Substantia_nigra_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Substantia_nigra_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Substantia_nigra_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Substantia_nigra_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Substantia_nigra_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Substantia_nigra_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Substantia_nigra_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Substantia_nigra_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Substantia_nigra_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Substantia_nigra_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Nucleus_accumbens_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Nucleus_accumbens_basal_ganglia_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Brain_Nucleus_accumbens_basal_ganglia_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Brain_Nucleus_accumbens_basal_ganglia_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Nucleus_accumbens_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Nucleus_accumbens_basal_ganglia_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Brain_Nucleus_accumbens_basal_ganglia_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Brain_Nucleus_accumbens_basal_ganglia_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Brain_Nucleus_accumbens_basal_ganglia_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Brain_Nucleus_accumbens_basal_ganglia_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Brain_Nucleus_accumbens_basal_ganglia_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Brain_Nucleus_accumbens_basal_ganglia_TRS" --subject="PrimeraLlengua"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Whole_Blood_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Whole_Blood_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Angles_Whole_Blood_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Angles_Whole_Blood_TRS" --subject="Angles"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Whole_Blood_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Whole_Blood_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/Matematiques_Whole_Blood_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="Matematiques_Whole_Blood_TRS" --subject="Matematiques"

Rscript TRS_FE.R --twas="/home/juditc/ADHD/GWAS_TDAH/TDAH/PRS_all_demontis_GWAS1_6/TRS_Demontis22_microarray_new/Results_TWAS/JTI_Whole_Blood_ADHD_ditte22_JTI_OR.csv" --marray="/home/juditc/ADHD/FE/TWAS/Whole_Blood_FE_predict_JTI_filtered.txt" --workingdir="/home/juditc/ADHD/FE/TRS" --clumplist="/home/juditc/ADHD/FE/TWAS/Clumping/PrimeraLlengua_Whole_Blood_Clumping_selected_genes.txt" --covar="/home/juditc/ADHD/FE/TWAS/final_covariates_gwas_4_2021_marray_PRS_corrected.csv" --output="PrimeraLlengua_Whole_Blood_TRS" --subject="PrimeraLlengua"






